/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_number,eslint_disable,ts_nocheck
// @generated from protobuf file "api.proto" (package "disctracking", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Ping } from "./hardware";
import { Timestamp } from "./google/protobuf/timestamp";
// ============ SESSION MESSAGES ============

/**
 * @generated from protobuf message disctracking.SessionRequest
 */
export interface SessionRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: string notes = 2
     */
    notes: string;
}
/**
 * @generated from protobuf message disctracking.SessionResponse
 */
export interface SessionResponse {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string;
    /**
     * @generated from protobuf field: string device_id = 3
     */
    deviceId: string;
    /**
     * @generated from protobuf field: string status = 4
     */
    status: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp started_at = 5
     */
    startedAt?: Timestamp;
    /**
     * @generated from protobuf field: optional google.protobuf.Timestamp ended_at = 6
     */
    endedAt?: Timestamp;
    /**
     * @generated from protobuf field: int32 throw_count = 7
     */
    throwCount: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 8
     */
    createdAt?: Timestamp;
}
/**
 * @generated from protobuf message disctracking.GetActiveSessionsResponse
 */
export interface GetActiveSessionsResponse {
    /**
     * @generated from protobuf field: repeated disctracking.SessionResponse sessions = 1
     */
    sessions: SessionResponse[];
}
/**
 * @generated from protobuf message disctracking.EndSessionRequest
 */
export interface EndSessionRequest {
    /**
     * @generated from protobuf field: string session_id = 1
     */
    sessionId: string;
}
/**
 * @generated from protobuf message disctracking.EndSessionResponse
 */
export interface EndSessionResponse {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp ended_at = 2
     */
    endedAt?: Timestamp;
}
// ============ DISC MESSAGES ============

/**
 * @generated from protobuf message disctracking.DiscRequest
 */
export interface DiscRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string type = 2
     */
    type: string;
    /**
     * @generated from protobuf field: int32 weight = 3
     */
    weight: number;
    /**
     * @generated from protobuf field: string color = 4
     */
    color: string;
}
/**
 * @generated from protobuf message disctracking.DiscResponse
 */
export interface DiscResponse {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string;
    /**
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * @generated from protobuf field: string type = 4
     */
    type: string;
    /**
     * @generated from protobuf field: int32 weight = 5
     */
    weight: number;
    /**
     * @generated from protobuf field: string color = 6
     */
    color: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 7
     */
    createdAt?: Timestamp;
}
/**
 * @generated from protobuf message disctracking.GetUserDiscsResponse
 */
export interface GetUserDiscsResponse {
    /**
     * @generated from protobuf field: repeated disctracking.DiscResponse discs = 1
     */
    discs: DiscResponse[];
}
/**
 * @generated from protobuf message disctracking.DeleteDiscRequest
 */
export interface DeleteDiscRequest {
    /**
     * @generated from protobuf field: string disc_id = 1
     */
    discId: string;
}
/**
 * @generated from protobuf message disctracking.DeleteDiscResponse
 */
export interface DeleteDiscResponse {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
    /**
     * @generated from protobuf field: string id = 2
     */
    id: string;
}
// ============ THROW MESSAGES ============

/**
 * @generated from protobuf message disctracking.ThrowRequest
 */
export interface ThrowRequest {
    /**
     * @generated from protobuf field: string session_id = 1
     */
    sessionId: string;
    /**
     * @generated from protobuf field: string disc_id = 2
     */
    discId: string;
    /**
     * @generated from protobuf field: double tee_lat = 3
     */
    teeLat: number;
    /**
     * @generated from protobuf field: double tee_lon = 4
     */
    teeLon: number;
    /**
     * @generated from protobuf field: optional double tee_alt = 5
     */
    teeAlt?: number;
    /**
     * @generated from protobuf field: double found_lat = 6
     */
    foundLat: number;
    /**
     * @generated from protobuf field: double found_lon = 7
     */
    foundLon: number;
    /**
     * @generated from protobuf field: optional double found_alt = 8
     */
    foundAlt?: number;
    /**
     * @generated from protobuf field: optional double distance = 9
     */
    distance?: number;
    /**
     * @generated from protobuf field: optional double max_rpm = 10
     */
    maxRpm?: number;
    /**
     * @generated from protobuf field: optional double exit_velocity = 11
     */
    exitVelocity?: number;
    /**
     * @generated from protobuf field: optional double flight_time = 12
     */
    flightTime?: number;
    /**
     * @generated from protobuf field: optional string state = 13
     */
    state?: string;
    /**
     * @generated from protobuf field: bool is_ob = 14
     */
    isOb: boolean;
    /**
     * @generated from protobuf field: optional double wobble_g = 15
     */
    wobbleG?: number;
    /**
     * @generated from protobuf field: optional double hdop = 16
     */
    hdop?: number;
}
/**
 * @generated from protobuf message disctracking.ThrowResponse
 */
export interface ThrowResponse {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
    /**
     * @generated from protobuf field: string id = 2
     */
    id: string;
}
/**
 * @generated from protobuf message disctracking.ThrowListItem
 */
export interface ThrowListItem {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string session_id = 2
     */
    sessionId: string;
    /**
     * @generated from protobuf field: string session_label = 3
     */
    sessionLabel: string;
    /**
     * @generated from protobuf field: string disc_name = 4
     */
    discName: string;
    /**
     * @generated from protobuf field: string disc_type = 5
     */
    discType: string;
    /**
     * @generated from protobuf field: double distance = 6
     */
    distance: number;
    /**
     * @generated from protobuf field: double flight_time = 7
     */
    flightTime: number;
    /**
     * @generated from protobuf field: double exit_velocity = 8
     */
    exitVelocity: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp timestamp = 9
     */
    timestamp?: Timestamp;
    /**
     * @generated from protobuf field: optional double max_rpm = 10
     */
    maxRpm?: number;
}
/**
 * @generated from protobuf message disctracking.GetThrowsResponse
 */
export interface GetThrowsResponse {
    /**
     * @generated from protobuf field: repeated disctracking.ThrowListItem throws = 1
     */
    throws: ThrowListItem[];
}
// ============ USER SETTINGS MESSAGES ============

/**
 * @generated from protobuf message disctracking.UserSettingsRequest
 */
export interface UserSettingsRequest {
    /**
     * @generated from protobuf field: optional double bag_location_lat = 1
     */
    bagLocationLat?: number;
    /**
     * @generated from protobuf field: optional double bag_location_lon = 2
     */
    bagLocationLon?: number;
    /**
     * @generated from protobuf field: string preferred_unit = 3
     */
    preferredUnit: string;
    /**
     * @generated from protobuf field: bool notifications_enabled = 4
     */
    notificationsEnabled: boolean;
    /**
     * @generated from protobuf field: bool auto_save_enabled = 5
     */
    autoSaveEnabled: boolean;
}
/**
 * @generated from protobuf message disctracking.UserSettingsResponse
 */
export interface UserSettingsResponse {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string;
    /**
     * @generated from protobuf field: optional double bag_location_lat = 3
     */
    bagLocationLat?: number;
    /**
     * @generated from protobuf field: optional double bag_location_lon = 4
     */
    bagLocationLon?: number;
    /**
     * @generated from protobuf field: string preferred_unit = 5
     */
    preferredUnit: string;
    /**
     * @generated from protobuf field: bool notifications_enabled = 6
     */
    notificationsEnabled: boolean;
    /**
     * @generated from protobuf field: bool auto_save_enabled = 7
     */
    autoSaveEnabled: boolean;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 8
     */
    updatedAt?: Timestamp;
}
// ============ USER MESSAGES ============

/**
 * @generated from protobuf message disctracking.UserResponse
 */
export interface UserResponse {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string email = 2
     */
    email: string;
    /**
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 4
     */
    createdAt?: Timestamp;
}
// ============ TELEMETRY MESSAGES ============

/**
 * @generated from protobuf message disctracking.TelemetryUpdate
 */
export interface TelemetryUpdate {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: double lat = 2
     */
    lat: number;
    /**
     * @generated from protobuf field: double lon = 3
     */
    lon: number;
    /**
     * @generated from protobuf field: optional double alt = 4
     */
    alt?: number;
    /**
     * @generated from protobuf field: double rpm = 5
     */
    rpm: number;
    /**
     * @generated from protobuf field: double wobble = 6
     */
    wobble: number;
    /**
     * @generated from protobuf field: int64 timestamp = 7
     */
    timestamp: number;
}
/**
 * @generated from protobuf message disctracking.GetTelemetryResponse
 */
export interface GetTelemetryResponse {
    /**
     * @generated from protobuf field: repeated disctracking.TelemetryUpdate telemetry = 1
     */
    telemetry: TelemetryUpdate[];
}
/**
 * @generated from protobuf message disctracking.TelemetryResponse
 */
export interface TelemetryResponse {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
    /**
     * @generated from protobuf field: int32 processed_count = 2
     */
    processedCount: number;
}
// ============ SYNC BATCH (for telemetry submission) ============

/**
 * @generated from protobuf message disctracking.SyncBatch
 */
export interface SyncBatch {
    /**
     * @generated from protobuf field: repeated disctracking.Ping pings = 1
     */
    pings: Ping[];
}
// @generated message type with reflection information, may provide speed optimized methods
class SessionRequest$Type extends MessageType<SessionRequest> {
    constructor() {
        super("disctracking.SessionRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "notes", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SessionRequest>): SessionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.notes = "";
        if (value !== undefined)
            reflectionMergePartial<SessionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SessionRequest): SessionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* string notes */ 2:
                    message.notes = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SessionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* string notes = 2; */
        if (message.notes !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.notes);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.SessionRequest
 */
export const SessionRequest = new SessionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SessionResponse$Type extends MessageType<SessionResponse> {
    constructor() {
        super("disctracking.SessionResponse", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "started_at", kind: "message", T: () => Timestamp },
            { no: 6, name: "ended_at", kind: "message", T: () => Timestamp },
            { no: 7, name: "throw_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "created_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<SessionResponse>): SessionResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.userId = "";
        message.deviceId = "";
        message.status = "";
        message.throwCount = 0;
        if (value !== undefined)
            reflectionMergePartial<SessionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SessionResponse): SessionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                case /* string device_id */ 3:
                    message.deviceId = reader.string();
                    break;
                case /* string status */ 4:
                    message.status = reader.string();
                    break;
                case /* google.protobuf.Timestamp started_at */ 5:
                    message.startedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.startedAt);
                    break;
                case /* optional google.protobuf.Timestamp ended_at */ 6:
                    message.endedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.endedAt);
                    break;
                case /* int32 throw_count */ 7:
                    message.throwCount = reader.int32();
                    break;
                case /* google.protobuf.Timestamp created_at */ 8:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SessionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* string device_id = 3; */
        if (message.deviceId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.deviceId);
        /* string status = 4; */
        if (message.status !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.status);
        /* google.protobuf.Timestamp started_at = 5; */
        if (message.startedAt)
            Timestamp.internalBinaryWrite(message.startedAt, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Timestamp ended_at = 6; */
        if (message.endedAt)
            Timestamp.internalBinaryWrite(message.endedAt, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* int32 throw_count = 7; */
        if (message.throwCount !== 0)
            writer.tag(7, WireType.Varint).int32(message.throwCount);
        /* google.protobuf.Timestamp created_at = 8; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.SessionResponse
 */
export const SessionResponse = new SessionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetActiveSessionsResponse$Type extends MessageType<GetActiveSessionsResponse> {
    constructor() {
        super("disctracking.GetActiveSessionsResponse", [
            { no: 1, name: "sessions", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => SessionResponse }
        ]);
    }
    create(value?: PartialMessage<GetActiveSessionsResponse>): GetActiveSessionsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sessions = [];
        if (value !== undefined)
            reflectionMergePartial<GetActiveSessionsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetActiveSessionsResponse): GetActiveSessionsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated disctracking.SessionResponse sessions */ 1:
                    message.sessions.push(SessionResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetActiveSessionsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated disctracking.SessionResponse sessions = 1; */
        for (let i = 0; i < message.sessions.length; i++)
            SessionResponse.internalBinaryWrite(message.sessions[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.GetActiveSessionsResponse
 */
export const GetActiveSessionsResponse = new GetActiveSessionsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EndSessionRequest$Type extends MessageType<EndSessionRequest> {
    constructor() {
        super("disctracking.EndSessionRequest", [
            { no: 1, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<EndSessionRequest>): EndSessionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sessionId = "";
        if (value !== undefined)
            reflectionMergePartial<EndSessionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EndSessionRequest): EndSessionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string session_id */ 1:
                    message.sessionId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EndSessionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string session_id = 1; */
        if (message.sessionId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.sessionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.EndSessionRequest
 */
export const EndSessionRequest = new EndSessionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EndSessionResponse$Type extends MessageType<EndSessionResponse> {
    constructor() {
        super("disctracking.EndSessionResponse", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "ended_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<EndSessionResponse>): EndSessionResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<EndSessionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EndSessionResponse): EndSessionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                case /* google.protobuf.Timestamp ended_at */ 2:
                    message.endedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.endedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EndSessionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        /* google.protobuf.Timestamp ended_at = 2; */
        if (message.endedAt)
            Timestamp.internalBinaryWrite(message.endedAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.EndSessionResponse
 */
export const EndSessionResponse = new EndSessionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DiscRequest$Type extends MessageType<DiscRequest> {
    constructor() {
        super("disctracking.DiscRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "weight", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "color", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DiscRequest>): DiscRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.type = "";
        message.weight = 0;
        message.color = "";
        if (value !== undefined)
            reflectionMergePartial<DiscRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DiscRequest): DiscRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string type */ 2:
                    message.type = reader.string();
                    break;
                case /* int32 weight */ 3:
                    message.weight = reader.int32();
                    break;
                case /* string color */ 4:
                    message.color = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DiscRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string type = 2; */
        if (message.type !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.type);
        /* int32 weight = 3; */
        if (message.weight !== 0)
            writer.tag(3, WireType.Varint).int32(message.weight);
        /* string color = 4; */
        if (message.color !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.color);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.DiscRequest
 */
export const DiscRequest = new DiscRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DiscResponse$Type extends MessageType<DiscResponse> {
    constructor() {
        super("disctracking.DiscResponse", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "weight", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "color", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "created_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<DiscResponse>): DiscResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.userId = "";
        message.name = "";
        message.type = "";
        message.weight = 0;
        message.color = "";
        if (value !== undefined)
            reflectionMergePartial<DiscResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DiscResponse): DiscResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* string type */ 4:
                    message.type = reader.string();
                    break;
                case /* int32 weight */ 5:
                    message.weight = reader.int32();
                    break;
                case /* string color */ 6:
                    message.color = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 7:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DiscResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* string type = 4; */
        if (message.type !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.type);
        /* int32 weight = 5; */
        if (message.weight !== 0)
            writer.tag(5, WireType.Varint).int32(message.weight);
        /* string color = 6; */
        if (message.color !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.color);
        /* google.protobuf.Timestamp created_at = 7; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.DiscResponse
 */
export const DiscResponse = new DiscResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserDiscsResponse$Type extends MessageType<GetUserDiscsResponse> {
    constructor() {
        super("disctracking.GetUserDiscsResponse", [
            { no: 1, name: "discs", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => DiscResponse }
        ]);
    }
    create(value?: PartialMessage<GetUserDiscsResponse>): GetUserDiscsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.discs = [];
        if (value !== undefined)
            reflectionMergePartial<GetUserDiscsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetUserDiscsResponse): GetUserDiscsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated disctracking.DiscResponse discs */ 1:
                    message.discs.push(DiscResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetUserDiscsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated disctracking.DiscResponse discs = 1; */
        for (let i = 0; i < message.discs.length; i++)
            DiscResponse.internalBinaryWrite(message.discs[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.GetUserDiscsResponse
 */
export const GetUserDiscsResponse = new GetUserDiscsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteDiscRequest$Type extends MessageType<DeleteDiscRequest> {
    constructor() {
        super("disctracking.DeleteDiscRequest", [
            { no: 1, name: "disc_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteDiscRequest>): DeleteDiscRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.discId = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteDiscRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteDiscRequest): DeleteDiscRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string disc_id */ 1:
                    message.discId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteDiscRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string disc_id = 1; */
        if (message.discId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.discId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.DeleteDiscRequest
 */
export const DeleteDiscRequest = new DeleteDiscRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteDiscResponse$Type extends MessageType<DeleteDiscResponse> {
    constructor() {
        super("disctracking.DeleteDiscResponse", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteDiscResponse>): DeleteDiscResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteDiscResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteDiscResponse): DeleteDiscResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                case /* string id */ 2:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteDiscResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        /* string id = 2; */
        if (message.id !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.DeleteDiscResponse
 */
export const DeleteDiscResponse = new DeleteDiscResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ThrowRequest$Type extends MessageType<ThrowRequest> {
    constructor() {
        super("disctracking.ThrowRequest", [
            { no: 1, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "disc_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "tee_lat", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "tee_lon", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "tee_alt", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "found_lat", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "found_lon", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 8, name: "found_alt", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 9, name: "distance", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 10, name: "max_rpm", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 11, name: "exit_velocity", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 12, name: "flight_time", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 13, name: "state", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "is_ob", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 15, name: "wobble_g", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 16, name: "hdop", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<ThrowRequest>): ThrowRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sessionId = "";
        message.discId = "";
        message.teeLat = 0;
        message.teeLon = 0;
        message.foundLat = 0;
        message.foundLon = 0;
        message.isOb = false;
        if (value !== undefined)
            reflectionMergePartial<ThrowRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ThrowRequest): ThrowRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string session_id */ 1:
                    message.sessionId = reader.string();
                    break;
                case /* string disc_id */ 2:
                    message.discId = reader.string();
                    break;
                case /* double tee_lat */ 3:
                    message.teeLat = reader.double();
                    break;
                case /* double tee_lon */ 4:
                    message.teeLon = reader.double();
                    break;
                case /* optional double tee_alt */ 5:
                    message.teeAlt = reader.double();
                    break;
                case /* double found_lat */ 6:
                    message.foundLat = reader.double();
                    break;
                case /* double found_lon */ 7:
                    message.foundLon = reader.double();
                    break;
                case /* optional double found_alt */ 8:
                    message.foundAlt = reader.double();
                    break;
                case /* optional double distance */ 9:
                    message.distance = reader.double();
                    break;
                case /* optional double max_rpm */ 10:
                    message.maxRpm = reader.double();
                    break;
                case /* optional double exit_velocity */ 11:
                    message.exitVelocity = reader.double();
                    break;
                case /* optional double flight_time */ 12:
                    message.flightTime = reader.double();
                    break;
                case /* optional string state */ 13:
                    message.state = reader.string();
                    break;
                case /* bool is_ob */ 14:
                    message.isOb = reader.bool();
                    break;
                case /* optional double wobble_g */ 15:
                    message.wobbleG = reader.double();
                    break;
                case /* optional double hdop */ 16:
                    message.hdop = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ThrowRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string session_id = 1; */
        if (message.sessionId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.sessionId);
        /* string disc_id = 2; */
        if (message.discId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.discId);
        /* double tee_lat = 3; */
        if (message.teeLat !== 0)
            writer.tag(3, WireType.Bit64).double(message.teeLat);
        /* double tee_lon = 4; */
        if (message.teeLon !== 0)
            writer.tag(4, WireType.Bit64).double(message.teeLon);
        /* optional double tee_alt = 5; */
        if (message.teeAlt !== undefined)
            writer.tag(5, WireType.Bit64).double(message.teeAlt);
        /* double found_lat = 6; */
        if (message.foundLat !== 0)
            writer.tag(6, WireType.Bit64).double(message.foundLat);
        /* double found_lon = 7; */
        if (message.foundLon !== 0)
            writer.tag(7, WireType.Bit64).double(message.foundLon);
        /* optional double found_alt = 8; */
        if (message.foundAlt !== undefined)
            writer.tag(8, WireType.Bit64).double(message.foundAlt);
        /* optional double distance = 9; */
        if (message.distance !== undefined)
            writer.tag(9, WireType.Bit64).double(message.distance);
        /* optional double max_rpm = 10; */
        if (message.maxRpm !== undefined)
            writer.tag(10, WireType.Bit64).double(message.maxRpm);
        /* optional double exit_velocity = 11; */
        if (message.exitVelocity !== undefined)
            writer.tag(11, WireType.Bit64).double(message.exitVelocity);
        /* optional double flight_time = 12; */
        if (message.flightTime !== undefined)
            writer.tag(12, WireType.Bit64).double(message.flightTime);
        /* optional string state = 13; */
        if (message.state !== undefined)
            writer.tag(13, WireType.LengthDelimited).string(message.state);
        /* bool is_ob = 14; */
        if (message.isOb !== false)
            writer.tag(14, WireType.Varint).bool(message.isOb);
        /* optional double wobble_g = 15; */
        if (message.wobbleG !== undefined)
            writer.tag(15, WireType.Bit64).double(message.wobbleG);
        /* optional double hdop = 16; */
        if (message.hdop !== undefined)
            writer.tag(16, WireType.Bit64).double(message.hdop);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.ThrowRequest
 */
export const ThrowRequest = new ThrowRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ThrowResponse$Type extends MessageType<ThrowResponse> {
    constructor() {
        super("disctracking.ThrowResponse", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ThrowResponse>): ThrowResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<ThrowResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ThrowResponse): ThrowResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                case /* string id */ 2:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ThrowResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        /* string id = 2; */
        if (message.id !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.ThrowResponse
 */
export const ThrowResponse = new ThrowResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ThrowListItem$Type extends MessageType<ThrowListItem> {
    constructor() {
        super("disctracking.ThrowListItem", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "session_label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "disc_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "disc_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "distance", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "flight_time", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 8, name: "exit_velocity", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 9, name: "timestamp", kind: "message", T: () => Timestamp },
            { no: 10, name: "max_rpm", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<ThrowListItem>): ThrowListItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.sessionId = "";
        message.sessionLabel = "";
        message.discName = "";
        message.discType = "";
        message.distance = 0;
        message.flightTime = 0;
        message.exitVelocity = 0;
        if (value !== undefined)
            reflectionMergePartial<ThrowListItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ThrowListItem): ThrowListItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string session_id */ 2:
                    message.sessionId = reader.string();
                    break;
                case /* string session_label */ 3:
                    message.sessionLabel = reader.string();
                    break;
                case /* string disc_name */ 4:
                    message.discName = reader.string();
                    break;
                case /* string disc_type */ 5:
                    message.discType = reader.string();
                    break;
                case /* double distance */ 6:
                    message.distance = reader.double();
                    break;
                case /* double flight_time */ 7:
                    message.flightTime = reader.double();
                    break;
                case /* double exit_velocity */ 8:
                    message.exitVelocity = reader.double();
                    break;
                case /* google.protobuf.Timestamp timestamp */ 9:
                    message.timestamp = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.timestamp);
                    break;
                case /* optional double max_rpm */ 10:
                    message.maxRpm = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ThrowListItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string session_id = 2; */
        if (message.sessionId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.sessionId);
        /* string session_label = 3; */
        if (message.sessionLabel !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.sessionLabel);
        /* string disc_name = 4; */
        if (message.discName !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.discName);
        /* string disc_type = 5; */
        if (message.discType !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.discType);
        /* double distance = 6; */
        if (message.distance !== 0)
            writer.tag(6, WireType.Bit64).double(message.distance);
        /* double flight_time = 7; */
        if (message.flightTime !== 0)
            writer.tag(7, WireType.Bit64).double(message.flightTime);
        /* double exit_velocity = 8; */
        if (message.exitVelocity !== 0)
            writer.tag(8, WireType.Bit64).double(message.exitVelocity);
        /* google.protobuf.Timestamp timestamp = 9; */
        if (message.timestamp)
            Timestamp.internalBinaryWrite(message.timestamp, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* optional double max_rpm = 10; */
        if (message.maxRpm !== undefined)
            writer.tag(10, WireType.Bit64).double(message.maxRpm);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.ThrowListItem
 */
export const ThrowListItem = new ThrowListItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetThrowsResponse$Type extends MessageType<GetThrowsResponse> {
    constructor() {
        super("disctracking.GetThrowsResponse", [
            { no: 1, name: "throws", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ThrowListItem }
        ]);
    }
    create(value?: PartialMessage<GetThrowsResponse>): GetThrowsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.throws = [];
        if (value !== undefined)
            reflectionMergePartial<GetThrowsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetThrowsResponse): GetThrowsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated disctracking.ThrowListItem throws */ 1:
                    message.throws.push(ThrowListItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetThrowsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated disctracking.ThrowListItem throws = 1; */
        for (let i = 0; i < message.throws.length; i++)
            ThrowListItem.internalBinaryWrite(message.throws[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.GetThrowsResponse
 */
export const GetThrowsResponse = new GetThrowsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserSettingsRequest$Type extends MessageType<UserSettingsRequest> {
    constructor() {
        super("disctracking.UserSettingsRequest", [
            { no: 1, name: "bag_location_lat", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "bag_location_lon", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "preferred_unit", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "notifications_enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "auto_save_enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<UserSettingsRequest>): UserSettingsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.preferredUnit = "";
        message.notificationsEnabled = false;
        message.autoSaveEnabled = false;
        if (value !== undefined)
            reflectionMergePartial<UserSettingsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserSettingsRequest): UserSettingsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional double bag_location_lat */ 1:
                    message.bagLocationLat = reader.double();
                    break;
                case /* optional double bag_location_lon */ 2:
                    message.bagLocationLon = reader.double();
                    break;
                case /* string preferred_unit */ 3:
                    message.preferredUnit = reader.string();
                    break;
                case /* bool notifications_enabled */ 4:
                    message.notificationsEnabled = reader.bool();
                    break;
                case /* bool auto_save_enabled */ 5:
                    message.autoSaveEnabled = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserSettingsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional double bag_location_lat = 1; */
        if (message.bagLocationLat !== undefined)
            writer.tag(1, WireType.Bit64).double(message.bagLocationLat);
        /* optional double bag_location_lon = 2; */
        if (message.bagLocationLon !== undefined)
            writer.tag(2, WireType.Bit64).double(message.bagLocationLon);
        /* string preferred_unit = 3; */
        if (message.preferredUnit !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.preferredUnit);
        /* bool notifications_enabled = 4; */
        if (message.notificationsEnabled !== false)
            writer.tag(4, WireType.Varint).bool(message.notificationsEnabled);
        /* bool auto_save_enabled = 5; */
        if (message.autoSaveEnabled !== false)
            writer.tag(5, WireType.Varint).bool(message.autoSaveEnabled);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.UserSettingsRequest
 */
export const UserSettingsRequest = new UserSettingsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserSettingsResponse$Type extends MessageType<UserSettingsResponse> {
    constructor() {
        super("disctracking.UserSettingsResponse", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "bag_location_lat", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "bag_location_lon", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "preferred_unit", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "notifications_enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "auto_save_enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "updated_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<UserSettingsResponse>): UserSettingsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.userId = "";
        message.preferredUnit = "";
        message.notificationsEnabled = false;
        message.autoSaveEnabled = false;
        if (value !== undefined)
            reflectionMergePartial<UserSettingsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserSettingsResponse): UserSettingsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                case /* optional double bag_location_lat */ 3:
                    message.bagLocationLat = reader.double();
                    break;
                case /* optional double bag_location_lon */ 4:
                    message.bagLocationLon = reader.double();
                    break;
                case /* string preferred_unit */ 5:
                    message.preferredUnit = reader.string();
                    break;
                case /* bool notifications_enabled */ 6:
                    message.notificationsEnabled = reader.bool();
                    break;
                case /* bool auto_save_enabled */ 7:
                    message.autoSaveEnabled = reader.bool();
                    break;
                case /* google.protobuf.Timestamp updated_at */ 8:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserSettingsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* optional double bag_location_lat = 3; */
        if (message.bagLocationLat !== undefined)
            writer.tag(3, WireType.Bit64).double(message.bagLocationLat);
        /* optional double bag_location_lon = 4; */
        if (message.bagLocationLon !== undefined)
            writer.tag(4, WireType.Bit64).double(message.bagLocationLon);
        /* string preferred_unit = 5; */
        if (message.preferredUnit !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.preferredUnit);
        /* bool notifications_enabled = 6; */
        if (message.notificationsEnabled !== false)
            writer.tag(6, WireType.Varint).bool(message.notificationsEnabled);
        /* bool auto_save_enabled = 7; */
        if (message.autoSaveEnabled !== false)
            writer.tag(7, WireType.Varint).bool(message.autoSaveEnabled);
        /* google.protobuf.Timestamp updated_at = 8; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.UserSettingsResponse
 */
export const UserSettingsResponse = new UserSettingsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserResponse$Type extends MessageType<UserResponse> {
    constructor() {
        super("disctracking.UserResponse", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "created_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<UserResponse>): UserResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.email = "";
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<UserResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserResponse): UserResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string email */ 2:
                    message.email = reader.string();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 4:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string email = 2; */
        if (message.email !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.email);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* google.protobuf.Timestamp created_at = 4; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.UserResponse
 */
export const UserResponse = new UserResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TelemetryUpdate$Type extends MessageType<TelemetryUpdate> {
    constructor() {
        super("disctracking.TelemetryUpdate", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "lat", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "lon", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "alt", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "rpm", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "wobble", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ }
        ]);
    }
    create(value?: PartialMessage<TelemetryUpdate>): TelemetryUpdate {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.lat = 0;
        message.lon = 0;
        message.rpm = 0;
        message.wobble = 0;
        message.timestamp = 0;
        if (value !== undefined)
            reflectionMergePartial<TelemetryUpdate>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TelemetryUpdate): TelemetryUpdate {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* double lat */ 2:
                    message.lat = reader.double();
                    break;
                case /* double lon */ 3:
                    message.lon = reader.double();
                    break;
                case /* optional double alt */ 4:
                    message.alt = reader.double();
                    break;
                case /* double rpm */ 5:
                    message.rpm = reader.double();
                    break;
                case /* double wobble */ 6:
                    message.wobble = reader.double();
                    break;
                case /* int64 timestamp */ 7:
                    message.timestamp = reader.int64().toNumber();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TelemetryUpdate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* double lat = 2; */
        if (message.lat !== 0)
            writer.tag(2, WireType.Bit64).double(message.lat);
        /* double lon = 3; */
        if (message.lon !== 0)
            writer.tag(3, WireType.Bit64).double(message.lon);
        /* optional double alt = 4; */
        if (message.alt !== undefined)
            writer.tag(4, WireType.Bit64).double(message.alt);
        /* double rpm = 5; */
        if (message.rpm !== 0)
            writer.tag(5, WireType.Bit64).double(message.rpm);
        /* double wobble = 6; */
        if (message.wobble !== 0)
            writer.tag(6, WireType.Bit64).double(message.wobble);
        /* int64 timestamp = 7; */
        if (message.timestamp !== 0)
            writer.tag(7, WireType.Varint).int64(message.timestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.TelemetryUpdate
 */
export const TelemetryUpdate = new TelemetryUpdate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTelemetryResponse$Type extends MessageType<GetTelemetryResponse> {
    constructor() {
        super("disctracking.GetTelemetryResponse", [
            { no: 1, name: "telemetry", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => TelemetryUpdate }
        ]);
    }
    create(value?: PartialMessage<GetTelemetryResponse>): GetTelemetryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.telemetry = [];
        if (value !== undefined)
            reflectionMergePartial<GetTelemetryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTelemetryResponse): GetTelemetryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated disctracking.TelemetryUpdate telemetry */ 1:
                    message.telemetry.push(TelemetryUpdate.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTelemetryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated disctracking.TelemetryUpdate telemetry = 1; */
        for (let i = 0; i < message.telemetry.length; i++)
            TelemetryUpdate.internalBinaryWrite(message.telemetry[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.GetTelemetryResponse
 */
export const GetTelemetryResponse = new GetTelemetryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TelemetryResponse$Type extends MessageType<TelemetryResponse> {
    constructor() {
        super("disctracking.TelemetryResponse", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "processed_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<TelemetryResponse>): TelemetryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        message.processedCount = 0;
        if (value !== undefined)
            reflectionMergePartial<TelemetryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TelemetryResponse): TelemetryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                case /* int32 processed_count */ 2:
                    message.processedCount = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TelemetryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        /* int32 processed_count = 2; */
        if (message.processedCount !== 0)
            writer.tag(2, WireType.Varint).int32(message.processedCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.TelemetryResponse
 */
export const TelemetryResponse = new TelemetryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SyncBatch$Type extends MessageType<SyncBatch> {
    constructor() {
        super("disctracking.SyncBatch", [
            { no: 1, name: "pings", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Ping }
        ]);
    }
    create(value?: PartialMessage<SyncBatch>): SyncBatch {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pings = [];
        if (value !== undefined)
            reflectionMergePartial<SyncBatch>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SyncBatch): SyncBatch {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated disctracking.Ping pings */ 1:
                    message.pings.push(Ping.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SyncBatch, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated disctracking.Ping pings = 1; */
        for (let i = 0; i < message.pings.length; i++)
            Ping.internalBinaryWrite(message.pings[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.SyncBatch
 */
export const SyncBatch = new SyncBatch$Type();
