/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_number,eslint_disable,ts_nocheck
// @generated from protobuf file "hardware.proto" (package "disctracking", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// ============ HARDWARE/TELEMETRY MESSAGES ============
// Field numbers MUST match firmware tracker.proto (nanopb)

/**
 * @generated from protobuf message disctracking.Ping
 */
export interface Ping {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * Spatial (GPS)
     *
     * @generated from protobuf field: double lat = 2
     */
    lat: number;
    /**
     * @generated from protobuf field: double lon = 3
     */
    lon: number;
    /**
     * @generated from protobuf field: double alt = 4
     */
    alt: number;
    /**
     * Velocity & Environment
     *
     * @generated from protobuf field: float speed_mps = 5
     */
    speedMps: number;
    /**
     * @generated from protobuf field: float heading = 6
     */
    heading: number;
    /**
     * @generated from protobuf field: float temp_c = 7
     */
    tempC: number;
    /**
     * Signal Quality
     *
     * @generated from protobuf field: float hdop = 8
     */
    hdop: number;
    /**
     * @generated from protobuf field: int32 sats = 9
     */
    sats: number;
    /**
     * Physics: Accelerometer (G-forces)
     *
     * @generated from protobuf field: float accel_x = 10
     */
    accelX: number;
    /**
     * @generated from protobuf field: float accel_y = 11
     */
    accelY: number;
    /**
     * @generated from protobuf field: float accel_z = 12
     */
    accelZ: number;
    /**
     * Physics: Gyroscope (degrees/sec)
     *
     * @generated from protobuf field: float gyro_x = 13
     */
    gyroX: number;
    /**
     * @generated from protobuf field: float gyro_y = 14
     */
    gyroY: number;
    /**
     * @generated from protobuf field: float gyro_z = 15
     */
    gyroZ: number;
    /**
     * @generated from protobuf field: int64 timestamp = 16
     */
    timestamp: number;
    /**
     * @generated from protobuf field: int32 batt_pct = 17
     */
    battPct: number;
}
/**
 * @generated from protobuf message disctracking.PingBatch
 */
export interface PingBatch {
    /**
     * @generated from protobuf field: repeated disctracking.Ping pings = 1
     */
    pings: Ping[];
    /**
     * @generated from protobuf field: string device_id = 2
     */
    deviceId: string;
    /**
     * @generated from protobuf field: int64 batch_timestamp = 3
     */
    batchTimestamp: number;
}
/**
 * Telemetry message envelope (legacy compatibility)
 *
 * @generated from protobuf message disctracking.ClientMessage
 */
export interface ClientMessage {
    /**
     * @generated from protobuf oneof: data
     */
    data: {
        oneofKind: "ping";
        /**
         * @generated from protobuf field: disctracking.Ping ping = 1
         */
        ping: Ping;
    } | {
        oneofKind: "batch";
        /**
         * @generated from protobuf field: disctracking.PingBatch batch = 2
         */
        batch: PingBatch;
    } | {
        oneofKind: "generic";
        /**
         * @generated from protobuf field: disctracking.GenericMessage generic = 3
         */
        generic: GenericMessage;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message disctracking.ServerMessage
 */
export interface ServerMessage {
    /**
     * @generated from protobuf oneof: data
     */
    data: {
        oneofKind: "status";
        /**
         * @generated from protobuf field: string status = 1
         */
        status: string;
    } | {
        oneofKind: "error";
        /**
         * @generated from protobuf field: disctracking.ErrorResponse error = 2
         */
        error: ErrorResponse;
    } | {
        oneofKind: "message";
        /**
         * @generated from protobuf field: disctracking.GenericMessage message = 3
         */
        message: GenericMessage;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message disctracking.GenericMessage
 */
export interface GenericMessage {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
}
/**
 * @generated from protobuf message disctracking.ErrorResponse
 */
export interface ErrorResponse {
    /**
     * @generated from protobuf field: string error = 1
     */
    error: string;
    /**
     * @generated from protobuf field: int32 code = 2
     */
    code: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class Ping$Type extends MessageType<Ping> {
    constructor() {
        super("disctracking.Ping", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "lat", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "lon", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "alt", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "speed_mps", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 6, name: "heading", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 7, name: "temp_c", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 8, name: "hdop", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 9, name: "sats", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "accel_x", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 11, name: "accel_y", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 12, name: "accel_z", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 13, name: "gyro_x", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 14, name: "gyro_y", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 15, name: "gyro_z", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 16, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 17, name: "batt_pct", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Ping>): Ping {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.lat = 0;
        message.lon = 0;
        message.alt = 0;
        message.speedMps = 0;
        message.heading = 0;
        message.tempC = 0;
        message.hdop = 0;
        message.sats = 0;
        message.accelX = 0;
        message.accelY = 0;
        message.accelZ = 0;
        message.gyroX = 0;
        message.gyroY = 0;
        message.gyroZ = 0;
        message.timestamp = 0;
        message.battPct = 0;
        if (value !== undefined)
            reflectionMergePartial<Ping>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Ping): Ping {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* double lat */ 2:
                    message.lat = reader.double();
                    break;
                case /* double lon */ 3:
                    message.lon = reader.double();
                    break;
                case /* double alt */ 4:
                    message.alt = reader.double();
                    break;
                case /* float speed_mps */ 5:
                    message.speedMps = reader.float();
                    break;
                case /* float heading */ 6:
                    message.heading = reader.float();
                    break;
                case /* float temp_c */ 7:
                    message.tempC = reader.float();
                    break;
                case /* float hdop */ 8:
                    message.hdop = reader.float();
                    break;
                case /* int32 sats */ 9:
                    message.sats = reader.int32();
                    break;
                case /* float accel_x */ 10:
                    message.accelX = reader.float();
                    break;
                case /* float accel_y */ 11:
                    message.accelY = reader.float();
                    break;
                case /* float accel_z */ 12:
                    message.accelZ = reader.float();
                    break;
                case /* float gyro_x */ 13:
                    message.gyroX = reader.float();
                    break;
                case /* float gyro_y */ 14:
                    message.gyroY = reader.float();
                    break;
                case /* float gyro_z */ 15:
                    message.gyroZ = reader.float();
                    break;
                case /* int64 timestamp */ 16:
                    message.timestamp = reader.int64().toNumber();
                    break;
                case /* int32 batt_pct */ 17:
                    message.battPct = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Ping, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* double lat = 2; */
        if (message.lat !== 0)
            writer.tag(2, WireType.Bit64).double(message.lat);
        /* double lon = 3; */
        if (message.lon !== 0)
            writer.tag(3, WireType.Bit64).double(message.lon);
        /* double alt = 4; */
        if (message.alt !== 0)
            writer.tag(4, WireType.Bit64).double(message.alt);
        /* float speed_mps = 5; */
        if (message.speedMps !== 0)
            writer.tag(5, WireType.Bit32).float(message.speedMps);
        /* float heading = 6; */
        if (message.heading !== 0)
            writer.tag(6, WireType.Bit32).float(message.heading);
        /* float temp_c = 7; */
        if (message.tempC !== 0)
            writer.tag(7, WireType.Bit32).float(message.tempC);
        /* float hdop = 8; */
        if (message.hdop !== 0)
            writer.tag(8, WireType.Bit32).float(message.hdop);
        /* int32 sats = 9; */
        if (message.sats !== 0)
            writer.tag(9, WireType.Varint).int32(message.sats);
        /* float accel_x = 10; */
        if (message.accelX !== 0)
            writer.tag(10, WireType.Bit32).float(message.accelX);
        /* float accel_y = 11; */
        if (message.accelY !== 0)
            writer.tag(11, WireType.Bit32).float(message.accelY);
        /* float accel_z = 12; */
        if (message.accelZ !== 0)
            writer.tag(12, WireType.Bit32).float(message.accelZ);
        /* float gyro_x = 13; */
        if (message.gyroX !== 0)
            writer.tag(13, WireType.Bit32).float(message.gyroX);
        /* float gyro_y = 14; */
        if (message.gyroY !== 0)
            writer.tag(14, WireType.Bit32).float(message.gyroY);
        /* float gyro_z = 15; */
        if (message.gyroZ !== 0)
            writer.tag(15, WireType.Bit32).float(message.gyroZ);
        /* int64 timestamp = 16; */
        if (message.timestamp !== 0)
            writer.tag(16, WireType.Varint).int64(message.timestamp);
        /* int32 batt_pct = 17; */
        if (message.battPct !== 0)
            writer.tag(17, WireType.Varint).int32(message.battPct);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.Ping
 */
export const Ping = new Ping$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PingBatch$Type extends MessageType<PingBatch> {
    constructor() {
        super("disctracking.PingBatch", [
            { no: 1, name: "pings", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Ping },
            { no: 2, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "batch_timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ }
        ]);
    }
    create(value?: PartialMessage<PingBatch>): PingBatch {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pings = [];
        message.deviceId = "";
        message.batchTimestamp = 0;
        if (value !== undefined)
            reflectionMergePartial<PingBatch>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PingBatch): PingBatch {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated disctracking.Ping pings */ 1:
                    message.pings.push(Ping.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string device_id */ 2:
                    message.deviceId = reader.string();
                    break;
                case /* int64 batch_timestamp */ 3:
                    message.batchTimestamp = reader.int64().toNumber();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PingBatch, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated disctracking.Ping pings = 1; */
        for (let i = 0; i < message.pings.length; i++)
            Ping.internalBinaryWrite(message.pings[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string device_id = 2; */
        if (message.deviceId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.deviceId);
        /* int64 batch_timestamp = 3; */
        if (message.batchTimestamp !== 0)
            writer.tag(3, WireType.Varint).int64(message.batchTimestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.PingBatch
 */
export const PingBatch = new PingBatch$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClientMessage$Type extends MessageType<ClientMessage> {
    constructor() {
        super("disctracking.ClientMessage", [
            { no: 1, name: "ping", kind: "message", oneof: "data", T: () => Ping },
            { no: 2, name: "batch", kind: "message", oneof: "data", T: () => PingBatch },
            { no: 3, name: "generic", kind: "message", oneof: "data", T: () => GenericMessage }
        ]);
    }
    create(value?: PartialMessage<ClientMessage>): ClientMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<ClientMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ClientMessage): ClientMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* disctracking.Ping ping */ 1:
                    message.data = {
                        oneofKind: "ping",
                        ping: Ping.internalBinaryRead(reader, reader.uint32(), options, (message.data as any).ping)
                    };
                    break;
                case /* disctracking.PingBatch batch */ 2:
                    message.data = {
                        oneofKind: "batch",
                        batch: PingBatch.internalBinaryRead(reader, reader.uint32(), options, (message.data as any).batch)
                    };
                    break;
                case /* disctracking.GenericMessage generic */ 3:
                    message.data = {
                        oneofKind: "generic",
                        generic: GenericMessage.internalBinaryRead(reader, reader.uint32(), options, (message.data as any).generic)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ClientMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* disctracking.Ping ping = 1; */
        if (message.data.oneofKind === "ping")
            Ping.internalBinaryWrite(message.data.ping, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* disctracking.PingBatch batch = 2; */
        if (message.data.oneofKind === "batch")
            PingBatch.internalBinaryWrite(message.data.batch, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* disctracking.GenericMessage generic = 3; */
        if (message.data.oneofKind === "generic")
            GenericMessage.internalBinaryWrite(message.data.generic, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.ClientMessage
 */
export const ClientMessage = new ClientMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ServerMessage$Type extends MessageType<ServerMessage> {
    constructor() {
        super("disctracking.ServerMessage", [
            { no: 1, name: "status", kind: "scalar", oneof: "data", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "error", kind: "message", oneof: "data", T: () => ErrorResponse },
            { no: 3, name: "message", kind: "message", oneof: "data", T: () => GenericMessage }
        ]);
    }
    create(value?: PartialMessage<ServerMessage>): ServerMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<ServerMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ServerMessage): ServerMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string status */ 1:
                    message.data = {
                        oneofKind: "status",
                        status: reader.string()
                    };
                    break;
                case /* disctracking.ErrorResponse error */ 2:
                    message.data = {
                        oneofKind: "error",
                        error: ErrorResponse.internalBinaryRead(reader, reader.uint32(), options, (message.data as any).error)
                    };
                    break;
                case /* disctracking.GenericMessage message */ 3:
                    message.data = {
                        oneofKind: "message",
                        message: GenericMessage.internalBinaryRead(reader, reader.uint32(), options, (message.data as any).message)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ServerMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string status = 1; */
        if (message.data.oneofKind === "status")
            writer.tag(1, WireType.LengthDelimited).string(message.data.status);
        /* disctracking.ErrorResponse error = 2; */
        if (message.data.oneofKind === "error")
            ErrorResponse.internalBinaryWrite(message.data.error, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* disctracking.GenericMessage message = 3; */
        if (message.data.oneofKind === "message")
            GenericMessage.internalBinaryWrite(message.data.message, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.ServerMessage
 */
export const ServerMessage = new ServerMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GenericMessage$Type extends MessageType<GenericMessage> {
    constructor() {
        super("disctracking.GenericMessage", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GenericMessage>): GenericMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<GenericMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GenericMessage): GenericMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GenericMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.GenericMessage
 */
export const GenericMessage = new GenericMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ErrorResponse$Type extends MessageType<ErrorResponse> {
    constructor() {
        super("disctracking.ErrorResponse", [
            { no: 1, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "code", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ErrorResponse>): ErrorResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.error = "";
        message.code = 0;
        if (value !== undefined)
            reflectionMergePartial<ErrorResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ErrorResponse): ErrorResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string error */ 1:
                    message.error = reader.string();
                    break;
                case /* int32 code */ 2:
                    message.code = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ErrorResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string error = 1; */
        if (message.error !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.error);
        /* int32 code = 2; */
        if (message.code !== 0)
            writer.tag(2, WireType.Varint).int32(message.code);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message disctracking.ErrorResponse
 */
export const ErrorResponse = new ErrorResponse$Type();
