syntax = "proto3";
package tracker;
option go_package = "./pb";

message Ping {
  string device_id = 1;   // Now injected automatically via hardware FICR!
  
  // Spatial
  double lat = 2;
  double lon = 3;
  double alt = 4;        
  
  // Velocity & Environment
  float speed_mps = 5;    // GPS Speed over ground
  float heading = 6;      // GPS Course over ground
  float temp_c = 7;       // IMU internal temperature
  
  // Signal Quality
  float hdop = 8;        
  int32 sats = 9;         // Satellites in view
  
  // Physics: Accelerometer (G-Forces)
  float accel_x = 10; 
  float accel_y = 11;
  float accel_z = 12; 
  
  // Physics: Gyroscope (Degrees per second)
  float gyro_x = 13;      // Pitch (Nose Up/Down)
  float gyro_y = 14;      // Roll (Hyzer/Anhyzer)
  float gyro_z = 15;      // Yaw (Spin Rate)
  
  int64 timestamp = 16;
}

message SyncBatch {
  repeated Ping pings = 1;
}