// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Notes         string                 `protobuf:"bytes,2,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *SessionRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SessionRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ended_at,json=endedAt,proto3,oneof" json:"ended_at,omitempty"`
	ThrowCount    int32                  `protobuf:"varint,7,opt,name=throw_count,json=throwCount,proto3" json:"throw_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *SessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SessionResponse) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *SessionResponse) GetThrowCount() int32 {
	if x != nil {
		return x.ThrowCount
	}
	return 0
}

func (x *SessionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetActiveSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionResponse     `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveSessionsResponse) Reset() {
	*x = GetActiveSessionsResponse{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSessionsResponse) ProtoMessage() {}

func (x *GetActiveSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetActiveSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetActiveSessionsResponse) GetSessions() []*SessionResponse {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type EndSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *EndSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EndSessionResponse) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

type DiscRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Weight        int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscRequest) Reset() {
	*x = DiscRequest{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscRequest) ProtoMessage() {}

func (x *DiscRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscRequest.ProtoReflect.Descriptor instead.
func (*DiscRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *DiscRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiscRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DiscRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *DiscRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type DiscResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Weight        int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscResponse) Reset() {
	*x = DiscResponse{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscResponse) ProtoMessage() {}

func (x *DiscResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscResponse.ProtoReflect.Descriptor instead.
func (*DiscResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *DiscResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiscResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DiscResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiscResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DiscResponse) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *DiscResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *DiscResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetUserDiscsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Discs         []*DiscResponse        `protobuf:"bytes,1,rep,name=discs,proto3" json:"discs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDiscsResponse) Reset() {
	*x = GetUserDiscsResponse{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDiscsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDiscsResponse) ProtoMessage() {}

func (x *GetUserDiscsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDiscsResponse.ProtoReflect.Descriptor instead.
func (*GetUserDiscsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserDiscsResponse) GetDiscs() []*DiscResponse {
	if x != nil {
		return x.Discs
	}
	return nil
}

type DeleteDiscRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiscId        string                 `protobuf:"bytes,1,opt,name=disc_id,json=discId,proto3" json:"disc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDiscRequest) Reset() {
	*x = DeleteDiscRequest{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDiscRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiscRequest) ProtoMessage() {}

func (x *DeleteDiscRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiscRequest.ProtoReflect.Descriptor instead.
func (*DeleteDiscRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDiscRequest) GetDiscId() string {
	if x != nil {
		return x.DiscId
	}
	return ""
}

type DeleteDiscResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDiscResponse) Reset() {
	*x = DeleteDiscResponse{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDiscResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiscResponse) ProtoMessage() {}

func (x *DeleteDiscResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiscResponse.ProtoReflect.Descriptor instead.
func (*DeleteDiscResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDiscResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteDiscResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ThrowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DiscId        string                 `protobuf:"bytes,2,opt,name=disc_id,json=discId,proto3" json:"disc_id,omitempty"`
	TeeLat        float64                `protobuf:"fixed64,3,opt,name=tee_lat,json=teeLat,proto3" json:"tee_lat,omitempty"`
	TeeLon        float64                `protobuf:"fixed64,4,opt,name=tee_lon,json=teeLon,proto3" json:"tee_lon,omitempty"`
	TeeAlt        *float64               `protobuf:"fixed64,5,opt,name=tee_alt,json=teeAlt,proto3,oneof" json:"tee_alt,omitempty"`
	FoundLat      float64                `protobuf:"fixed64,6,opt,name=found_lat,json=foundLat,proto3" json:"found_lat,omitempty"`
	FoundLon      float64                `protobuf:"fixed64,7,opt,name=found_lon,json=foundLon,proto3" json:"found_lon,omitempty"`
	FoundAlt      *float64               `protobuf:"fixed64,8,opt,name=found_alt,json=foundAlt,proto3,oneof" json:"found_alt,omitempty"`
	Distance      *float64               `protobuf:"fixed64,9,opt,name=distance,proto3,oneof" json:"distance,omitempty"`
	MaxRpm        *float64               `protobuf:"fixed64,10,opt,name=max_rpm,json=maxRpm,proto3,oneof" json:"max_rpm,omitempty"`
	ExitVelocity  *float64               `protobuf:"fixed64,11,opt,name=exit_velocity,json=exitVelocity,proto3,oneof" json:"exit_velocity,omitempty"`
	FlightTime    *float64               `protobuf:"fixed64,12,opt,name=flight_time,json=flightTime,proto3,oneof" json:"flight_time,omitempty"`
	State         *string                `protobuf:"bytes,13,opt,name=state,proto3,oneof" json:"state,omitempty"`
	IsOb          bool                   `protobuf:"varint,14,opt,name=is_ob,json=isOb,proto3" json:"is_ob,omitempty"`
	WobbleG       *float64               `protobuf:"fixed64,15,opt,name=wobble_g,json=wobbleG,proto3,oneof" json:"wobble_g,omitempty"`
	Hdop          *float64               `protobuf:"fixed64,16,opt,name=hdop,proto3,oneof" json:"hdop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThrowRequest) Reset() {
	*x = ThrowRequest{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrowRequest) ProtoMessage() {}

func (x *ThrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrowRequest.ProtoReflect.Descriptor instead.
func (*ThrowRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *ThrowRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ThrowRequest) GetDiscId() string {
	if x != nil {
		return x.DiscId
	}
	return ""
}

func (x *ThrowRequest) GetTeeLat() float64 {
	if x != nil {
		return x.TeeLat
	}
	return 0
}

func (x *ThrowRequest) GetTeeLon() float64 {
	if x != nil {
		return x.TeeLon
	}
	return 0
}

func (x *ThrowRequest) GetTeeAlt() float64 {
	if x != nil && x.TeeAlt != nil {
		return *x.TeeAlt
	}
	return 0
}

func (x *ThrowRequest) GetFoundLat() float64 {
	if x != nil {
		return x.FoundLat
	}
	return 0
}

func (x *ThrowRequest) GetFoundLon() float64 {
	if x != nil {
		return x.FoundLon
	}
	return 0
}

func (x *ThrowRequest) GetFoundAlt() float64 {
	if x != nil && x.FoundAlt != nil {
		return *x.FoundAlt
	}
	return 0
}

func (x *ThrowRequest) GetDistance() float64 {
	if x != nil && x.Distance != nil {
		return *x.Distance
	}
	return 0
}

func (x *ThrowRequest) GetMaxRpm() float64 {
	if x != nil && x.MaxRpm != nil {
		return *x.MaxRpm
	}
	return 0
}

func (x *ThrowRequest) GetExitVelocity() float64 {
	if x != nil && x.ExitVelocity != nil {
		return *x.ExitVelocity
	}
	return 0
}

func (x *ThrowRequest) GetFlightTime() float64 {
	if x != nil && x.FlightTime != nil {
		return *x.FlightTime
	}
	return 0
}

func (x *ThrowRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *ThrowRequest) GetIsOb() bool {
	if x != nil {
		return x.IsOb
	}
	return false
}

func (x *ThrowRequest) GetWobbleG() float64 {
	if x != nil && x.WobbleG != nil {
		return *x.WobbleG
	}
	return 0
}

func (x *ThrowRequest) GetHdop() float64 {
	if x != nil && x.Hdop != nil {
		return *x.Hdop
	}
	return 0
}

type ThrowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThrowResponse) Reset() {
	*x = ThrowResponse{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrowResponse) ProtoMessage() {}

func (x *ThrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrowResponse.ProtoReflect.Descriptor instead.
func (*ThrowResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *ThrowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ThrowResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserSettingsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BagLocationLat       *float64               `protobuf:"fixed64,1,opt,name=bag_location_lat,json=bagLocationLat,proto3,oneof" json:"bag_location_lat,omitempty"`
	BagLocationLon       *float64               `protobuf:"fixed64,2,opt,name=bag_location_lon,json=bagLocationLon,proto3,oneof" json:"bag_location_lon,omitempty"`
	PreferredUnit        string                 `protobuf:"bytes,3,opt,name=preferred_unit,json=preferredUnit,proto3" json:"preferred_unit,omitempty"`
	NotificationsEnabled bool                   `protobuf:"varint,4,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	AutoSaveEnabled      bool                   `protobuf:"varint,5,opt,name=auto_save_enabled,json=autoSaveEnabled,proto3" json:"auto_save_enabled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserSettingsRequest) Reset() {
	*x = UserSettingsRequest{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettingsRequest) ProtoMessage() {}

func (x *UserSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettingsRequest.ProtoReflect.Descriptor instead.
func (*UserSettingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *UserSettingsRequest) GetBagLocationLat() float64 {
	if x != nil && x.BagLocationLat != nil {
		return *x.BagLocationLat
	}
	return 0
}

func (x *UserSettingsRequest) GetBagLocationLon() float64 {
	if x != nil && x.BagLocationLon != nil {
		return *x.BagLocationLon
	}
	return 0
}

func (x *UserSettingsRequest) GetPreferredUnit() string {
	if x != nil {
		return x.PreferredUnit
	}
	return ""
}

func (x *UserSettingsRequest) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *UserSettingsRequest) GetAutoSaveEnabled() bool {
	if x != nil {
		return x.AutoSaveEnabled
	}
	return false
}

type UserSettingsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BagLocationLat       *float64               `protobuf:"fixed64,3,opt,name=bag_location_lat,json=bagLocationLat,proto3,oneof" json:"bag_location_lat,omitempty"`
	BagLocationLon       *float64               `protobuf:"fixed64,4,opt,name=bag_location_lon,json=bagLocationLon,proto3,oneof" json:"bag_location_lon,omitempty"`
	PreferredUnit        string                 `protobuf:"bytes,5,opt,name=preferred_unit,json=preferredUnit,proto3" json:"preferred_unit,omitempty"`
	NotificationsEnabled bool                   `protobuf:"varint,6,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	AutoSaveEnabled      bool                   `protobuf:"varint,7,opt,name=auto_save_enabled,json=autoSaveEnabled,proto3" json:"auto_save_enabled,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserSettingsResponse) Reset() {
	*x = UserSettingsResponse{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettingsResponse) ProtoMessage() {}

func (x *UserSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettingsResponse.ProtoReflect.Descriptor instead.
func (*UserSettingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *UserSettingsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSettingsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSettingsResponse) GetBagLocationLat() float64 {
	if x != nil && x.BagLocationLat != nil {
		return *x.BagLocationLat
	}
	return 0
}

func (x *UserSettingsResponse) GetBagLocationLon() float64 {
	if x != nil && x.BagLocationLon != nil {
		return *x.BagLocationLon
	}
	return 0
}

func (x *UserSettingsResponse) GetPreferredUnit() string {
	if x != nil {
		return x.PreferredUnit
	}
	return ""
}

func (x *UserSettingsResponse) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *UserSettingsResponse) GetAutoSaveEnabled() bool {
	if x != nil {
		return x.AutoSaveEnabled
	}
	return false
}

func (x *UserSettingsResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GenericMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericMessage) Reset() {
	*x = GenericMessage{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericMessage) ProtoMessage() {}

func (x *GenericMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericMessage.ProtoReflect.Descriptor instead.
func (*GenericMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *GenericMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GenericId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericId) Reset() {
	*x = GenericId{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericId) ProtoMessage() {}

func (x *GenericId) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericId.ProtoReflect.Descriptor instead.
func (*GenericId) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *GenericId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\fdisctracking\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x0eSessionRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05notes\x18\x02 \x01(\tR\x05notes\"\xcf\x02\n" +
	"\x0fSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12:\n" +
	"\bended_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\aendedAt\x88\x01\x01\x12\x1f\n" +
	"\vthrow_count\x18\a \x01(\x05R\n" +
	"throwCount\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\v\n" +
	"\t_ended_at\"V\n" +
	"\x19GetActiveSessionsResponse\x129\n" +
	"\bsessions\x18\x01 \x03(\v2\x1d.disctracking.SessionResponseR\bsessions\"2\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"e\n" +
	"\x12EndSessionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x125\n" +
	"\bended_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\"c\n" +
	"\vDiscRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\"\xc8\x01\n" +
	"\fDiscResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"H\n" +
	"\x14GetUserDiscsResponse\x120\n" +
	"\x05discs\x18\x01 \x03(\v2\x1a.disctracking.DiscResponseR\x05discs\",\n" +
	"\x11DeleteDiscRequest\x12\x17\n" +
	"\adisc_id\x18\x01 \x01(\tR\x06discId\">\n" +
	"\x12DeleteDiscResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xdf\x04\n" +
	"\fThrowRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\adisc_id\x18\x02 \x01(\tR\x06discId\x12\x17\n" +
	"\atee_lat\x18\x03 \x01(\x01R\x06teeLat\x12\x17\n" +
	"\atee_lon\x18\x04 \x01(\x01R\x06teeLon\x12\x1c\n" +
	"\atee_alt\x18\x05 \x01(\x01H\x00R\x06teeAlt\x88\x01\x01\x12\x1b\n" +
	"\tfound_lat\x18\x06 \x01(\x01R\bfoundLat\x12\x1b\n" +
	"\tfound_lon\x18\a \x01(\x01R\bfoundLon\x12 \n" +
	"\tfound_alt\x18\b \x01(\x01H\x01R\bfoundAlt\x88\x01\x01\x12\x1f\n" +
	"\bdistance\x18\t \x01(\x01H\x02R\bdistance\x88\x01\x01\x12\x1c\n" +
	"\amax_rpm\x18\n" +
	" \x01(\x01H\x03R\x06maxRpm\x88\x01\x01\x12(\n" +
	"\rexit_velocity\x18\v \x01(\x01H\x04R\fexitVelocity\x88\x01\x01\x12$\n" +
	"\vflight_time\x18\f \x01(\x01H\x05R\n" +
	"flightTime\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\r \x01(\tH\x06R\x05state\x88\x01\x01\x12\x13\n" +
	"\x05is_ob\x18\x0e \x01(\bR\x04isOb\x12\x1e\n" +
	"\bwobble_g\x18\x0f \x01(\x01H\aR\awobbleG\x88\x01\x01\x12\x17\n" +
	"\x04hdop\x18\x10 \x01(\x01H\bR\x04hdop\x88\x01\x01B\n" +
	"\n" +
	"\b_tee_altB\f\n" +
	"\n" +
	"_found_altB\v\n" +
	"\t_distanceB\n" +
	"\n" +
	"\b_max_rpmB\x10\n" +
	"\x0e_exit_velocityB\x0e\n" +
	"\f_flight_timeB\b\n" +
	"\x06_stateB\v\n" +
	"\t_wobble_gB\a\n" +
	"\x05_hdop\"9\n" +
	"\rThrowResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xa5\x02\n" +
	"\x13UserSettingsRequest\x12-\n" +
	"\x10bag_location_lat\x18\x01 \x01(\x01H\x00R\x0ebagLocationLat\x88\x01\x01\x12-\n" +
	"\x10bag_location_lon\x18\x02 \x01(\x01H\x01R\x0ebagLocationLon\x88\x01\x01\x12%\n" +
	"\x0epreferred_unit\x18\x03 \x01(\tR\rpreferredUnit\x123\n" +
	"\x15notifications_enabled\x18\x04 \x01(\bR\x14notificationsEnabled\x12*\n" +
	"\x11auto_save_enabled\x18\x05 \x01(\bR\x0fautoSaveEnabledB\x13\n" +
	"\x11_bag_location_latB\x13\n" +
	"\x11_bag_location_lon\"\x8a\x03\n" +
	"\x14UserSettingsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12-\n" +
	"\x10bag_location_lat\x18\x03 \x01(\x01H\x00R\x0ebagLocationLat\x88\x01\x01\x12-\n" +
	"\x10bag_location_lon\x18\x04 \x01(\x01H\x01R\x0ebagLocationLon\x88\x01\x01\x12%\n" +
	"\x0epreferred_unit\x18\x05 \x01(\tR\rpreferredUnit\x123\n" +
	"\x15notifications_enabled\x18\x06 \x01(\bR\x14notificationsEnabled\x12*\n" +
	"\x11auto_save_enabled\x18\a \x01(\bR\x0fautoSaveEnabled\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x13\n" +
	"\x11_bag_location_latB\x13\n" +
	"\x11_bag_location_lon\"\x83\x01\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"9\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"*\n" +
	"\x0eGenericMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1b\n" +
	"\tGenericId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB$Z\"project2/disc-tracking-software/pbb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_goTypes = []any{
	(*SessionRequest)(nil),            // 0: disctracking.SessionRequest
	(*SessionResponse)(nil),           // 1: disctracking.SessionResponse
	(*GetActiveSessionsResponse)(nil), // 2: disctracking.GetActiveSessionsResponse
	(*EndSessionRequest)(nil),         // 3: disctracking.EndSessionRequest
	(*EndSessionResponse)(nil),        // 4: disctracking.EndSessionResponse
	(*DiscRequest)(nil),               // 5: disctracking.DiscRequest
	(*DiscResponse)(nil),              // 6: disctracking.DiscResponse
	(*GetUserDiscsResponse)(nil),      // 7: disctracking.GetUserDiscsResponse
	(*DeleteDiscRequest)(nil),         // 8: disctracking.DeleteDiscRequest
	(*DeleteDiscResponse)(nil),        // 9: disctracking.DeleteDiscResponse
	(*ThrowRequest)(nil),              // 10: disctracking.ThrowRequest
	(*ThrowResponse)(nil),             // 11: disctracking.ThrowResponse
	(*UserSettingsRequest)(nil),       // 12: disctracking.UserSettingsRequest
	(*UserSettingsResponse)(nil),      // 13: disctracking.UserSettingsResponse
	(*UserResponse)(nil),              // 14: disctracking.UserResponse
	(*ErrorResponse)(nil),             // 15: disctracking.ErrorResponse
	(*GenericMessage)(nil),            // 16: disctracking.GenericMessage
	(*GenericId)(nil),                 // 17: disctracking.GenericId
	(*timestamppb.Timestamp)(nil),     // 18: google.protobuf.Timestamp
}
var file_api_proto_depIdxs = []int32{
	18, // 0: disctracking.SessionResponse.started_at:type_name -> google.protobuf.Timestamp
	18, // 1: disctracking.SessionResponse.ended_at:type_name -> google.protobuf.Timestamp
	18, // 2: disctracking.SessionResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 3: disctracking.GetActiveSessionsResponse.sessions:type_name -> disctracking.SessionResponse
	18, // 4: disctracking.EndSessionResponse.ended_at:type_name -> google.protobuf.Timestamp
	18, // 5: disctracking.DiscResponse.created_at:type_name -> google.protobuf.Timestamp
	6,  // 6: disctracking.GetUserDiscsResponse.discs:type_name -> disctracking.DiscResponse
	18, // 7: disctracking.UserSettingsResponse.updated_at:type_name -> google.protobuf.Timestamp
	18, // 8: disctracking.UserResponse.created_at:type_name -> google.protobuf.Timestamp
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_proto_msgTypes[12].OneofWrappers = []any{}
	file_api_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
