// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.0
// source: hardware.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId        string   `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Timestamp       int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AccelX          float32  `protobuf:"fixed32,3,opt,name=accel_x,json=accelX,proto3" json:"accel_x,omitempty"`
	AccelY          float32  `protobuf:"fixed32,4,opt,name=accel_y,json=accelY,proto3" json:"accel_y,omitempty"`
	AccelZ          float32  `protobuf:"fixed32,5,opt,name=accel_z,json=accelZ,proto3" json:"accel_z,omitempty"`
	GyroX           float32  `protobuf:"fixed32,6,opt,name=gyro_x,json=gyroX,proto3" json:"gyro_x,omitempty"`
	GyroY           float32  `protobuf:"fixed32,7,opt,name=gyro_y,json=gyroY,proto3" json:"gyro_y,omitempty"`
	GyroZ           float32  `protobuf:"fixed32,8,opt,name=gyro_z,json=gyroZ,proto3" json:"gyro_z,omitempty"`
	MagX            *float32 `protobuf:"fixed32,9,opt,name=mag_x,json=magX,proto3,oneof" json:"mag_x,omitempty"`
	MagY            *float32 `protobuf:"fixed32,10,opt,name=mag_y,json=magY,proto3,oneof" json:"mag_y,omitempty"`
	MagZ            *float32 `protobuf:"fixed32,11,opt,name=mag_z,json=magZ,proto3,oneof" json:"mag_z,omitempty"`
	Latitude        *float64 `protobuf:"fixed64,12,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude       *float64 `protobuf:"fixed64,13,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	Altitude        *float64 `protobuf:"fixed64,14,opt,name=altitude,proto3,oneof" json:"altitude,omitempty"`
	Hdop            *float32 `protobuf:"fixed32,15,opt,name=hdop,proto3,oneof" json:"hdop,omitempty"`
	Satellites      *int32   `protobuf:"varint,16,opt,name=satellites,proto3,oneof" json:"satellites,omitempty"`
	BatteryPercent  int32    `protobuf:"varint,17,opt,name=battery_percent,json=batteryPercent,proto3" json:"battery_percent,omitempty"`
	SignalStrength  int32    `protobuf:"varint,18,opt,name=signal_strength,json=signalStrength,proto3" json:"signal_strength,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hardware_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringer(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Ping) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Ping) GetAccelX() float32 {
	if x != nil {
		return x.AccelX
	}
	return 0
}

func (x *Ping) GetAccelY() float32 {
	if x != nil {
		return x.AccelY
	}
	return 0
}

func (x *Ping) GetAccelZ() float32 {
	if x != nil {
		return x.AccelZ
	}
	return 0
}

func (x *Ping) GetGyroX() float32 {
	if x != nil {
		return x.GyroX
	}
	return 0
}

func (x *Ping) GetGyroY() float32 {
	if x != nil {
		return x.GyroY
	}
	return 0
}

func (x *Ping) GetGyroZ() float32 {
	if x != nil {
		return x.GyroZ
	}
	return 0
}

func (x *Ping) GetMagX() float32 {
	if x != nil && x.MagX != nil {
		return *x.MagX
	}
	return 0
}

func (x *Ping) GetMagY() float32 {
	if x != nil && x.MagY != nil {
		return *x.MagY
	}
	return 0
}

func (x *Ping) GetMagZ() float32 {
	if x != nil && x.MagZ != nil {
		return *x.MagZ
	}
	return 0
}

func (x *Ping) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *Ping) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *Ping) GetAltitude() float64 {
	if x != nil && x.Altitude != nil {
		return *x.Altitude
	}
	return 0
}

func (x *Ping) GetHdop() float32 {
	if x != nil && x.Hdop != nil {
		return *x.Hdop
	}
	return 0
}

func (x *Ping) GetSatellites() int32 {
	if x != nil && x.Satellites != nil {
		return *x.Satellites
	}
	return 0
}

func (x *Ping) GetBatteryPercent() int32 {
	if x != nil {
		return x.BatteryPercent
	}
	return 0
}

func (x *Ping) GetSignalStrength() int32 {
	if x != nil {
		return x.SignalStrength
	}
	return 0
}

var File_hardware_proto protoreflect.FileDescriptor

var (
	file_hardware_proto_rawDesc = []byte{
		// This would be actual protobuf binary
	}
)

var (
	file_hardware_proto_msgTypes make([]protoimpl.MessageInfo, 4)
	file_hardware_proto_goTypes  []interface{}
	file_hardware_proto_depIdxs  map[int][]int32
)

func init() {
	file_hardware_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
		switch v := v.(type) {
		case *Ping:
			return &v.state
		default:
			return nil
		}
	}
}

type x struct{}

func (x) One_Ping() {}
