// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: hardware.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Spatial (GPS)
	Lat float64 `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon float64 `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt float64 `protobuf:"fixed64,4,opt,name=alt,proto3" json:"alt,omitempty"`
	// Velocity & Environment
	SpeedMps float32 `protobuf:"fixed32,5,opt,name=speed_mps,json=speedMps,proto3" json:"speed_mps,omitempty"`
	Heading  float32 `protobuf:"fixed32,6,opt,name=heading,proto3" json:"heading,omitempty"`
	TempC    float32 `protobuf:"fixed32,7,opt,name=temp_c,json=tempC,proto3" json:"temp_c,omitempty"`
	// Signal Quality
	Hdop float32 `protobuf:"fixed32,8,opt,name=hdop,proto3" json:"hdop,omitempty"`
	Sats int32   `protobuf:"varint,9,opt,name=sats,proto3" json:"sats,omitempty"`
	// Physics: Accelerometer (G-forces)
	AccelX float32 `protobuf:"fixed32,10,opt,name=accel_x,json=accelX,proto3" json:"accel_x,omitempty"`
	AccelY float32 `protobuf:"fixed32,11,opt,name=accel_y,json=accelY,proto3" json:"accel_y,omitempty"`
	AccelZ float32 `protobuf:"fixed32,12,opt,name=accel_z,json=accelZ,proto3" json:"accel_z,omitempty"`
	// Physics: Gyroscope (degrees/sec)
	GyroX         float32 `protobuf:"fixed32,13,opt,name=gyro_x,json=gyroX,proto3" json:"gyro_x,omitempty"`
	GyroY         float32 `protobuf:"fixed32,14,opt,name=gyro_y,json=gyroY,proto3" json:"gyro_y,omitempty"`
	GyroZ         float32 `protobuf:"fixed32,15,opt,name=gyro_z,json=gyroZ,proto3" json:"gyro_z,omitempty"`
	Timestamp     int64   `protobuf:"varint,16,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BattPct       int32   `protobuf:"varint,17,opt,name=batt_pct,json=battPct,proto3" json:"batt_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_hardware_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Ping) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Ping) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Ping) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *Ping) GetSpeedMps() float32 {
	if x != nil {
		return x.SpeedMps
	}
	return 0
}

func (x *Ping) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *Ping) GetTempC() float32 {
	if x != nil {
		return x.TempC
	}
	return 0
}

func (x *Ping) GetHdop() float32 {
	if x != nil {
		return x.Hdop
	}
	return 0
}

func (x *Ping) GetSats() int32 {
	if x != nil {
		return x.Sats
	}
	return 0
}

func (x *Ping) GetAccelX() float32 {
	if x != nil {
		return x.AccelX
	}
	return 0
}

func (x *Ping) GetAccelY() float32 {
	if x != nil {
		return x.AccelY
	}
	return 0
}

func (x *Ping) GetAccelZ() float32 {
	if x != nil {
		return x.AccelZ
	}
	return 0
}

func (x *Ping) GetGyroX() float32 {
	if x != nil {
		return x.GyroX
	}
	return 0
}

func (x *Ping) GetGyroY() float32 {
	if x != nil {
		return x.GyroY
	}
	return 0
}

func (x *Ping) GetGyroZ() float32 {
	if x != nil {
		return x.GyroZ
	}
	return 0
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Ping) GetBattPct() int32 {
	if x != nil {
		return x.BattPct
	}
	return 0
}

type PingBatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pings          []*Ping                `protobuf:"bytes,1,rep,name=pings,proto3" json:"pings,omitempty"`
	DeviceId       string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	BatchTimestamp int64                  `protobuf:"varint,3,opt,name=batch_timestamp,json=batchTimestamp,proto3" json:"batch_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PingBatch) Reset() {
	*x = PingBatch{}
	mi := &file_hardware_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingBatch) ProtoMessage() {}

func (x *PingBatch) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingBatch.ProtoReflect.Descriptor instead.
func (*PingBatch) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{1}
}

func (x *PingBatch) GetPings() []*Ping {
	if x != nil {
		return x.Pings
	}
	return nil
}

func (x *PingBatch) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PingBatch) GetBatchTimestamp() int64 {
	if x != nil {
		return x.BatchTimestamp
	}
	return 0
}

// Telemetry message envelope (legacy compatibility)
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ClientMessage_Ping
	//	*ClientMessage_Batch
	//	*ClientMessage_Generic
	Data          isClientMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_hardware_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{2}
}

func (x *ClientMessage) GetData() isClientMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClientMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Data.(*ClientMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ClientMessage) GetBatch() *PingBatch {
	if x != nil {
		if x, ok := x.Data.(*ClientMessage_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

func (x *ClientMessage) GetGeneric() *GenericMessage {
	if x != nil {
		if x, ok := x.Data.(*ClientMessage_Generic); ok {
			return x.Generic
		}
	}
	return nil
}

type isClientMessage_Data interface {
	isClientMessage_Data()
}

type ClientMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type ClientMessage_Batch struct {
	Batch *PingBatch `protobuf:"bytes,2,opt,name=batch,proto3,oneof"`
}

type ClientMessage_Generic struct {
	Generic *GenericMessage `protobuf:"bytes,3,opt,name=generic,proto3,oneof"`
}

func (*ClientMessage_Ping) isClientMessage_Data() {}

func (*ClientMessage_Batch) isClientMessage_Data() {}

func (*ClientMessage_Generic) isClientMessage_Data() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ServerMessage_Status
	//	*ServerMessage_Error
	//	*ServerMessage_Message
	Data          isServerMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_hardware_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{3}
}

func (x *ServerMessage) GetData() isServerMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ServerMessage) GetStatus() string {
	if x != nil {
		if x, ok := x.Data.(*ServerMessage_Status); ok {
			return x.Status
		}
	}
	return ""
}

func (x *ServerMessage) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Data.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerMessage) GetMessage() *GenericMessage {
	if x != nil {
		if x, ok := x.Data.(*ServerMessage_Message); ok {
			return x.Message
		}
	}
	return nil
}

type isServerMessage_Data interface {
	isServerMessage_Data()
}

type ServerMessage_Status struct {
	Status string `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type ServerMessage_Message struct {
	Message *GenericMessage `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

func (*ServerMessage_Status) isServerMessage_Data() {}

func (*ServerMessage_Error) isServerMessage_Data() {}

func (*ServerMessage_Message) isServerMessage_Data() {}

type GenericMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericMessage) Reset() {
	*x = GenericMessage{}
	mi := &file_hardware_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericMessage) ProtoMessage() {}

func (x *GenericMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericMessage.ProtoReflect.Descriptor instead.
func (*GenericMessage) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{4}
}

func (x *GenericMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_hardware_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_hardware_proto protoreflect.FileDescriptor

const file_hardware_proto_rawDesc = "" +
	"\n" +
	"\x0ehardware.proto\x12\fdisctracking\"\x98\x03\n" +
	"\x04Ping\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\x04 \x01(\x01R\x03alt\x12\x1b\n" +
	"\tspeed_mps\x18\x05 \x01(\x02R\bspeedMps\x12\x18\n" +
	"\aheading\x18\x06 \x01(\x02R\aheading\x12\x15\n" +
	"\x06temp_c\x18\a \x01(\x02R\x05tempC\x12\x12\n" +
	"\x04hdop\x18\b \x01(\x02R\x04hdop\x12\x12\n" +
	"\x04sats\x18\t \x01(\x05R\x04sats\x12\x17\n" +
	"\aaccel_x\x18\n" +
	" \x01(\x02R\x06accelX\x12\x17\n" +
	"\aaccel_y\x18\v \x01(\x02R\x06accelY\x12\x17\n" +
	"\aaccel_z\x18\f \x01(\x02R\x06accelZ\x12\x15\n" +
	"\x06gyro_x\x18\r \x01(\x02R\x05gyroX\x12\x15\n" +
	"\x06gyro_y\x18\x0e \x01(\x02R\x05gyroY\x12\x15\n" +
	"\x06gyro_z\x18\x0f \x01(\x02R\x05gyroZ\x12\x1c\n" +
	"\ttimestamp\x18\x10 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bbatt_pct\x18\x11 \x01(\x05R\abattPct\"{\n" +
	"\tPingBatch\x12(\n" +
	"\x05pings\x18\x01 \x03(\v2\x12.disctracking.PingR\x05pings\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12'\n" +
	"\x0fbatch_timestamp\x18\x03 \x01(\x03R\x0ebatchTimestamp\"\xac\x01\n" +
	"\rClientMessage\x12(\n" +
	"\x04ping\x18\x01 \x01(\v2\x12.disctracking.PingH\x00R\x04ping\x12/\n" +
	"\x05batch\x18\x02 \x01(\v2\x17.disctracking.PingBatchH\x00R\x05batch\x128\n" +
	"\ageneric\x18\x03 \x01(\v2\x1c.disctracking.GenericMessageH\x00R\agenericB\x06\n" +
	"\x04data\"\xa0\x01\n" +
	"\rServerMessage\x12\x18\n" +
	"\x06status\x18\x01 \x01(\tH\x00R\x06status\x123\n" +
	"\x05error\x18\x02 \x01(\v2\x1b.disctracking.ErrorResponseH\x00R\x05error\x128\n" +
	"\amessage\x18\x03 \x01(\v2\x1c.disctracking.GenericMessageH\x00R\amessageB\x06\n" +
	"\x04data\"*\n" +
	"\x0eGenericMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"9\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04codeB$Z\"project2/disc-tracking-software/pbb\x06proto3"

var (
	file_hardware_proto_rawDescOnce sync.Once
	file_hardware_proto_rawDescData []byte
)

func file_hardware_proto_rawDescGZIP() []byte {
	file_hardware_proto_rawDescOnce.Do(func() {
		file_hardware_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hardware_proto_rawDesc), len(file_hardware_proto_rawDesc)))
	})
	return file_hardware_proto_rawDescData
}

var file_hardware_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_hardware_proto_goTypes = []any{
	(*Ping)(nil),           // 0: disctracking.Ping
	(*PingBatch)(nil),      // 1: disctracking.PingBatch
	(*ClientMessage)(nil),  // 2: disctracking.ClientMessage
	(*ServerMessage)(nil),  // 3: disctracking.ServerMessage
	(*GenericMessage)(nil), // 4: disctracking.GenericMessage
	(*ErrorResponse)(nil),  // 5: disctracking.ErrorResponse
}
var file_hardware_proto_depIdxs = []int32{
	0, // 0: disctracking.PingBatch.pings:type_name -> disctracking.Ping
	0, // 1: disctracking.ClientMessage.ping:type_name -> disctracking.Ping
	1, // 2: disctracking.ClientMessage.batch:type_name -> disctracking.PingBatch
	4, // 3: disctracking.ClientMessage.generic:type_name -> disctracking.GenericMessage
	5, // 4: disctracking.ServerMessage.error:type_name -> disctracking.ErrorResponse
	4, // 5: disctracking.ServerMessage.message:type_name -> disctracking.GenericMessage
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_hardware_proto_init() }
func file_hardware_proto_init() {
	if File_hardware_proto != nil {
		return
	}
	file_hardware_proto_msgTypes[2].OneofWrappers = []any{
		(*ClientMessage_Ping)(nil),
		(*ClientMessage_Batch)(nil),
		(*ClientMessage_Generic)(nil),
	}
	file_hardware_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerMessage_Status)(nil),
		(*ServerMessage_Error)(nil),
		(*ServerMessage_Message)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hardware_proto_rawDesc), len(file_hardware_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hardware_proto_goTypes,
		DependencyIndexes: file_hardware_proto_depIdxs,
		MessageInfos:      file_hardware_proto_msgTypes,
	}.Build()
	File_hardware_proto = out.File
	file_hardware_proto_goTypes = nil
	file_hardware_proto_depIdxs = nil
}
