// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: tracker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// object representing characteristics of what is captured in a single GPS ping from disc
type Ping struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Latitude       float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude       float64                `protobuf:"fixed64,4,opt,name=altitude,proto3" json:"altitude,omitempty"`                                    //alt in meters
	Hdop           float32                `protobuf:"fixed32,5,opt,name=hdop,proto3" json:"hdop,omitempty"`                                            //horizontal Dilution of Precision
	Sats           int32                  `protobuf:"varint,6,opt,name=sats,proto3" json:"sats,omitempty"`                                             //satellite number
	Speed          float32                `protobuf:"fixed32,7,opt,name=speed,proto3" json:"speed,omitempty"`                                          //velocity of GPS/GNSS in m/s
	AccelX         float64                `protobuf:"fixed64,8,opt,name=accel_x,json=accelX,proto3" json:"accel_x,omitempty"`                          //IMU | accelerometer in x
	AccelY         float64                `protobuf:"fixed64,9,opt,name=accel_y,json=accelY,proto3" json:"accel_y,omitempty"`                          //IMU | accelerometer in x
	AccelZ         float64                `protobuf:"fixed64,10,opt,name=accel_z,json=accelZ,proto3" json:"accel_z,omitempty"`                         //IMU | accelerometer in z, clean release here will show as a flat z-axis, Off Axis Torque (OAT) will show high
	FrequencyNoise float64                `protobuf:"fixed64,11,opt,name=frequency_noise,json=frequencyNoise,proto3" json:"frequency_noise,omitempty"` //Delay to avoid fake throws/ acccidental registers
	Timestamp      int64                  `protobuf:"varint,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                  //epoch time
	Battery        int32                  `protobuf:"varint,13,opt,name=battery,proto3" json:"battery,omitempty"`                                      //millivolts
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Ping) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Ping) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Ping) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *Ping) GetHdop() float32 {
	if x != nil {
		return x.Hdop
	}
	return 0
}

func (x *Ping) GetSats() int32 {
	if x != nil {
		return x.Sats
	}
	return 0
}

func (x *Ping) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Ping) GetAccelX() float64 {
	if x != nil {
		return x.AccelX
	}
	return 0
}

func (x *Ping) GetAccelY() float64 {
	if x != nil {
		return x.AccelY
	}
	return 0
}

func (x *Ping) GetAccelZ() float64 {
	if x != nil {
		return x.AccelZ
	}
	return 0
}

func (x *Ping) GetFrequencyNoise() float64 {
	if x != nil {
		return x.FrequencyNoise
	}
	return 0
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Ping) GetBattery() int32 {
	if x != nil {
		return x.Battery
	}
	return 0
}

// burst binary transfer when phone is in range
type SyncBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pings         []*Ping                `protobuf:"bytes,1,rep,name=pings,proto3" json:"pings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncBatch) Reset() {
	*x = SyncBatch{}
	mi := &file_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBatch) ProtoMessage() {}

func (x *SyncBatch) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBatch.ProtoReflect.Descriptor instead.
func (*SyncBatch) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *SyncBatch) GetPings() []*Ping {
	if x != nil {
		return x.Pings
	}
	return nil
}

// Server updates about throw phase (e.g. IN_FLIGHT, LANDED)
type ThrowStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThrowStatus) Reset() {
	*x = ThrowStatus{}
	mi := &file_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThrowStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrowStatus) ProtoMessage() {}

func (x *ThrowStatus) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrowStatus.ProtoReflect.Descriptor instead.
func (*ThrowStatus) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *ThrowStatus) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ThrowStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Server telemetry updates after processing
type TelemetryUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	Rpm           float64                `protobuf:"fixed64,4,opt,name=rpm,proto3" json:"rpm,omitempty"`
	Wobble        float64                `protobuf:"fixed64,5,opt,name=wobble,proto3" json:"wobble,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryUpdate) Reset() {
	*x = TelemetryUpdate{}
	mi := &file_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryUpdate) ProtoMessage() {}

func (x *TelemetryUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryUpdate.ProtoReflect.Descriptor instead.
func (*TelemetryUpdate) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryUpdate) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TelemetryUpdate) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *TelemetryUpdate) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *TelemetryUpdate) GetRpm() float64 {
	if x != nil {
		return x.Rpm
	}
	return 0
}

func (x *TelemetryUpdate) GetWobble() float64 {
	if x != nil {
		return x.Wobble
	}
	return 0
}

var File_tracker_proto protoreflect.FileDescriptor

const file_tracker_proto_rawDesc = "" +
	"\n" +
	"\rtracker.proto\x12\atracker\"\xe3\x02\n" +
	"\x04Ping\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x04 \x01(\x01R\baltitude\x12\x12\n" +
	"\x04hdop\x18\x05 \x01(\x02R\x04hdop\x12\x12\n" +
	"\x04sats\x18\x06 \x01(\x05R\x04sats\x12\x14\n" +
	"\x05speed\x18\a \x01(\x02R\x05speed\x12\x17\n" +
	"\aaccel_x\x18\b \x01(\x01R\x06accelX\x12\x17\n" +
	"\aaccel_y\x18\t \x01(\x01R\x06accelY\x12\x17\n" +
	"\aaccel_z\x18\n" +
	" \x01(\x01R\x06accelZ\x12'\n" +
	"\x0ffrequency_noise\x18\v \x01(\x01R\x0efrequencyNoise\x12\x1c\n" +
	"\ttimestamp\x18\f \x01(\x03R\ttimestamp\x12\x18\n" +
	"\abattery\x18\r \x01(\x05R\abattery\"0\n" +
	"\tSyncBatch\x12#\n" +
	"\x05pings\x18\x01 \x03(\v2\r.tracker.PingR\x05pings\"B\n" +
	"\vThrowStatus\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"|\n" +
	"\x0fTelemetryUpdate\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03rpm\x18\x04 \x01(\x01R\x03rpm\x12\x16\n" +
	"\x06wobble\x18\x05 \x01(\x01R\x06wobbleB\x06Z\x04./pbb\x06proto3"

var (
	file_tracker_proto_rawDescOnce sync.Once
	file_tracker_proto_rawDescData []byte
)

func file_tracker_proto_rawDescGZIP() []byte {
	file_tracker_proto_rawDescOnce.Do(func() {
		file_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)))
	})
	return file_tracker_proto_rawDescData
}

var file_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tracker_proto_goTypes = []any{
	(*Ping)(nil),            // 0: tracker.Ping
	(*SyncBatch)(nil),       // 1: tracker.SyncBatch
	(*ThrowStatus)(nil),     // 2: tracker.ThrowStatus
	(*TelemetryUpdate)(nil), // 3: tracker.TelemetryUpdate
}
var file_tracker_proto_depIdxs = []int32{
	0, // 0: tracker.SyncBatch.pings:type_name -> tracker.Ping
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tracker_proto_init() }
func file_tracker_proto_init() {
	if File_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tracker_proto_goTypes,
		DependencyIndexes: file_tracker_proto_depIdxs,
		MessageInfos:      file_tracker_proto_msgTypes,
	}.Build()
	File_tracker_proto = out.File
	file_tracker_proto_goTypes = nil
	file_tracker_proto_depIdxs = nil
}
